### ISSUE TITLE
V9 Crash When Adjusting Arpeggiator Rate

### ISSUE THREAD

**Issue by rds2024-3004** [zsteinkamp/m4l-Knobbler4#13]
Hi,
I just discovered that the V9 is crashing when using an arpeggiator device, for example. It doesn't matter if the arpeggiator is on the same chain. When you adjust the rate of the arpeggiator, it crashes immediately. I'm not sure if this is a bug, but I just wanted to bring it up.

Thanks.

**Comment by zsteinkamp** [comment]
Thanks for the bug report! 

I had been noticing sometimes garbage characters in the Current Param Value string value display but wasn't motivated enough to fix it. Turns out I was errantly scaling the parameter value as reported by the parameter object in calling `str_for_value` on the Parameter to get the string representation of the value to push to the tablet's Current Param display.

In the case of Arpeggiator, the rate knob would report a value between 0-14, but I was scaling that to 0-196 then requesting the string representation. There seems to be a lack of bounds checking in the str_for_value implementation, and Max/Live will happily look up a value well outside the Min/Max range. I'll report this to Ableton.

The fix was to eliminate the errant `[scale]` object and just look up the value as reported by the parameter.

You can download the updated device in [v10](https://github.com/zsteinkamp/m4l-Knobbler4/releases/tag/v10).

Thanks again!
