### ISSUE TITLE
Control works, but no labels

### ISSUE THREAD

**Issue by unremarkablegarden** [zsteinkamp/m4l-Knobbler4#8]
Dear Zack, 
Love what you're doing with this project!

I have an issue with setup. I've followed your instructions step by step, several times, but end up at an inpasse. I have:

- Latest TouchOSC
- Latest Knobbler layout loaded
- Latest Max 8
- Latest Max For Live Knobbler
- Ableton 12.0

I've set up the network connection. The iPad finds the computer. The M4L device finds my iPad. Using the 192... IP. I set the ports.

Now when I select, Frequency on the Drift synth, then touch the first slider on the first tab of Kobbler, it lets me control that parameter, but there is no label or colour update on Knobbler. 

Knobbler remains looking like when it's first loaded blankly: 
--- --- --- for all parameters. If I go to bluhand I can control the various parameters of Drift, but no labels are loaded.

Any ideas?

**Comment by unremarkablegarden** [comment]
Hmm. Strange. I had renamed Knobbler4.amxd to Knobbler4-v5.amxd. After renaming it back to the original name and reloading it it's working!

**Comment by unremarkablegarden** [comment]
Another thing I just thought of that would be very cool is an iPhone version of the layout. 926 x 428 pixels. One "row" of controls on each page. Trying to resize it myself now in TouchOSC editor but it looks quite complicated to do. Knobbler mini :)

**Comment by zsteinkamp** [comment]
Hey @unremarkablegarden thanks for getting in touch!

When you can move a TouchOSC slider and successfully control a parameter, but colors and labels don't update on the iPad that is a signal that the computer-to-iPad connection is not working. This is usually due to either the wrong hostname/port in the Knobbler4 device, or your WiFi configuration prevents the uPnP (mDNS) auto-discovery from working.

I'm not sure what the problem was in your case, but I'm certain that it was not due to the name of the device. Is it possible that when you first loaded the Knobbler4 device that you did not have TouchOSC configured and running in the foreground on the iPad?

Has it worked since that first time?

As far as a small-screen view, I'd be happy to include that if you or someone else made it. My focus in the coming month or so is to make a native app. TouchOSC is awesome for DIY projects, but its cost and complexity for "normal" users is higher than I'd like. The native app would lay out its screens algorithmically, so it's possible it could adapt to small screen sizes more easily.

As you use it more, if you have ideas run into more issues with Knobbler, please let me know. Screenshots, screen recordings, etc can be very helpful to diagnose problems remotely.
